# Site Settings
title: Kritika Iyer
url: 'https://iyerkritika.github.io'
# baseurl: '/webpage' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
style: styles-3
# style: styles-4
# style: styles-5
# style: styles-6

#Profile information
name: Kritika Iyer
tagline: Graduate student at WPI
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I am a Robotics graduate student at WPI(Worcester Polytechnic Institute) and intend to graduate in May 2018. I am currently looking for a full time job focusing on Deep learning and perception. I have experience coding in C++ and Python, my most recent project includes training a neural network to detect emotions."

#sidebar links
email: kiyer@wpi.edu
phone: 774 701 2616
# website: blog.webjeda.com #do not add http://
linkedin: kritikaiyer
github: iyerkritika
# twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
