# Site Settings
title: Kritika Iyer
url: 'https://iyerkritika.github.io'
# baseurl: '/webpage' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
style: styles-3
# style: styles-4
# style: styles-5
# style: styles-6

#Profile information
name: Kritika Iyer
tagline: Software Engineer at FESTO
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: I am a Software Engineer at FESTO corporation. I deal with their kinematics and liquid handling systems for their Medical Laboratory branch. I did my Master's degree in Robotics Engineering from WPI(Worcester Polytechnic Institute). I am currently looking for a full time job focusing on Deep learning and perception. I have experience coding in C++ and Python, my most recent projects include creating test benches with graphical interfaces as well as using Deep Learning to detect the emotions and attention levels of children with ASD. I am a fast learner and an efficient worker. I have assisted in over 6 projects at FESTO in just 7 months. FESTO Boston being a small branch works in a start-up environment setup and has given me experience in doing different parts of the project and working as a team towards the same goal.

#sidebar links
email: kiyer@wpi.edu
phone: 774 701 2616
# website: blog.webjeda.com #do not add http://
linkedin: kritikaiyer
github: iyerkritika
# twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
