# Site Settings
title: Kritika Iyer
url: 'https://iyerkritika.github.io'
# baseurl: '/webpage' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
style: styles-3
# style: styles-4
# style: styles-5
# style: styles-6

#Profile information
name: Kritika Iyer
tagline: Software Engineer at FESTO
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: I am a Software Engineer at Medacuity Software LLC. I deal with various projects pertaining to the medical device industry. I did my Master's degree in Robotics Engineering from WPI(Worcester Polytechnic Institute). I have experience coding in C++ and Python, C# and .Net, my most recent projects include creating graphical interfaces for medical devices as well as using Deep Learning to detect the emotions and attention levels of children with ASD. I am a fast learner and an efficient worker. In the last 2 years, I have developed my skills in C# and C++ considerably and learned a lot about what it takes to make a product in the medical device industry. Having worked in a start-up and currently working in a medium-sized company I know how to adapt and work in any environment and understand the challenges and advantages of these scenarios. I am very self-sufficient and believe I have the caliber to be able to transfer knowledge to newer employees.

#sidebar links
email: kiyer@wpi.edu
phone: 774 701 2616
# website: blog.webjeda.com #do not add http://
linkedin: kritikaiyer
github: iyerkritika
# twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
